// Code generated by goyacc -v y.output -o parser.go -p rule parser.y. DO NOT EDIT.

//line parser.y:1

package rulekit

import __yyfmt__ "fmt"

//line parser.y:3

import (
	"fmt"
	"io"
	"net"
	"os"
	"regexp"
	"strconv"
	"strings"
)

var ruleDebugWriter io.Writer = os.Stderr

func init() {
	SetErrorVerbose(true) // default to true
}

// SetDebugLevel sets the debug verbosity level
func SetDebugLevel(level int) {
	ruleDebug = level
}

func SetDebugWriter(w io.Writer) {
	ruleDebugWriter = w
}

// SetErrorVerbose enables or disables verbose error reporting
func SetErrorVerbose(verbose bool) {
	ruleErrorVerbose = verbose
}

func operatorToString(op int) string {
	switch op {
	case op_EQ:
		return "=="
	case op_NE:
		return "!="
	case op_GT:
		return ">"
	case op_GE:
		return ">="
	case op_LT:
		return "<"
	case op_LE:
		return "<="
	case op_CONTAINS:
		return "contains"
	case op_MATCHES:
		return "matches"
	case op_IN:
		return "in"
	default:
		return "unknown"
	}
}

func withNegate(negate bool, node Rule) Rule {
	if negate {
		return &nodeNot{right: node}
	}
	return node
}

// Add these type-specific parsing functions in the Go code section
func parseString[T interface{ string | []byte }](data T) (string, error) {
	raw_value := string(data)
	if raw_value[0] == '\'' {
		// Convert single-quoted string to double-quoted
		inner := raw_value[1 : len(raw_value)-1]
		escaped := strings.ReplaceAll(inner, `"`, "\\\"")
		escaped = strings.ReplaceAll(escaped, `\'`, `'`)
		raw_value = `"` + escaped + `"`
	}
	return strconv.Unquote(raw_value)
}

func parseInt[T interface{ string | []byte }](data T) (any, error) {
	raw_value := string(data)
	if n, err := strconv.ParseInt(raw_value, 0, 64); err == nil {
		return n, nil
	}
	if n, err := strconv.ParseUint(raw_value, 0, 64); err == nil {
		return n, nil
	}
	return nil, fmt.Errorf("parsing integer: invalid value %q", raw_value)
}

func parseFloat[T interface{ string | []byte }](data T) (float64, error) {
	return strconv.ParseFloat(string(data), 64)
}

func parseBool[T interface{ string | []byte }](data T) (bool, error) {
	raw_value := string(data)
	if strings.EqualFold(raw_value, "true") {
		return true, nil
	}
	if strings.EqualFold(raw_value, "false") {
		return false, nil
	}
	return false, fmt.Errorf("parsing boolean: unknown value %q", raw_value)
}

func parseRegex[T interface{ string | []byte }](data T) (*regexp.Regexp, error) {
	raw_value := string(data)
	pattern := raw_value[1 : len(raw_value)-1] // Remove the forward slashes
	return regexp.Compile(pattern)
}

// Add a new type to represent parsed values
type parsedValue struct {
	raw_value string
	value     any
}

// Helper to format array raw value nicely
func formatArrayRawValue(elements []parsedValue) string {
	parts := make([]string, len(elements))
	for i, elem := range elements {
		parts[i] = elem.raw_value
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func extractValues(elements []parsedValue) []any {
	values := make([]any, len(elements))
	for i, elem := range elements {
		values[i] = elem.value
	}
	return values
}

func parseToken(token_type int, data []byte) (parsedValue, error) {
	var (
		raw   = string(data)
		value any
		err   error
	)
	switch token_type {
	case token_STRING:
		value, err = parseString(data)
	case token_INT:
		value, err = parseInt(data)
	case token_FLOAT:
		value, err = parseFloat(data)
	case token_BOOL:
		value, err = parseBool(data)
	case token_IP:
		if value = net.ParseIP(raw); value == nil {
			err = fmt.Errorf("invalid IP value %q", raw)
		}
	case token_IP_CIDR:
		_, value, err = net.ParseCIDR(raw)
	case token_HEX_STRING:
		value, err = ParseHexString(raw)
	case token_REGEX:
		value, err = parseRegex(data)
	default:
		err = fmt.Errorf("unsupported token type %d", token_type)
	}
	if err != nil {
		return parsedValue{}, fmt.Errorf("parsing %s: %v", tokenTypeString(token_type), err)
	}
	return parsedValue{raw_value: raw, value: value}, nil
}

// Add token type struct for mid-rule actions
type tokenType struct {
	typ  int
	data []byte
}

func tokenTypeString(typ int) string {
	switch typ {
	case token_STRING:
		return "string"
	case token_INT:
		return "integer"
	case token_FLOAT:
		return "float"
	case token_BOOL:
		return "boolean"
	case token_IP:
		return "IP"
	case token_IP_CIDR:
		return "CIDR"
	case token_HEX_STRING:
		return "hex string"
	case token_REGEX:
		return "regex"
	default:
		return "unknown"
	}
}

//line parser.y:198
type ruleSymType struct {
	yys        int
	rule       Rule
	data       []byte
	operator   int
	negate     bool
	arrayElems []parsedValue // Change type from []any to []parsedValue
	tokType    tokenType     // Add new type for mid-rule actions
}

const token_FIELD = 57346
const token_STRING = 57347
const token_HEX_STRING = 57348
const token_INT = 57349
const token_FLOAT = 57350
const token_BOOL = 57351
const token_IP_CIDR = 57352
const token_IP = 57353
const token_REGEX = 57354
const op_NOT = 57355
const op_AND = 57356
const op_OR = 57357
const token_LPAREN = 57358
const token_RPAREN = 57359
const token_LBRACKET = 57360
const token_RBRACKET = 57361
const token_COMMA = 57362
const op_EQ = 57363
const op_NE = 57364
const op_GT = 57365
const op_GE = 57366
const op_LT = 57367
const op_LE = 57368
const op_CONTAINS = 57369
const op_MATCHES = 57370
const op_IN = 57371
const token_ERROR = 57372

var ruleToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"token_FIELD",
	"token_STRING",
	"token_HEX_STRING",
	"token_INT",
	"token_FLOAT",
	"token_BOOL",
	"token_IP_CIDR",
	"token_IP",
	"token_REGEX",
	"op_NOT",
	"op_AND",
	"op_OR",
	"token_LPAREN",
	"token_RPAREN",
	"token_LBRACKET",
	"token_RBRACKET",
	"token_COMMA",
	"op_EQ",
	"op_NE",
	"op_GT",
	"op_GE",
	"op_LT",
	"op_LE",
	"op_CONTAINS",
	"op_MATCHES",
	"op_IN",
	"token_ERROR",
}

var ruleStatenames = [...]string{}

const ruleEofCode = 1
const ruleErrCode = 2
const ruleInitialStackSize = 16

//line parser.y:519

//line yacctab:1
var ruleExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 5,
	1, 14,
	14, 14,
	15, 14,
	17, 14,
	-2, 26,
}

const rulePrivate = 57344

const ruleLast = 55

var ruleAct = [...]int8{
	38, 19, 20, 23, 24, 25, 26, 21, 17, 18,
	37, 27, 28, 50, 49, 29, 31, 30, 48, 49,
	36, 5, 6, 7, 32, 14, 6, 7, 7, 11,
	3, 35, 39, 4, 40, 46, 41, 42, 43, 45,
	44, 1, 33, 34, 10, 8, 9, 47, 12, 13,
	51, 15, 22, 16, 2,
}

var rulePact = [...]int16{
	17, 12, -1000, 17, 17, 16, 17, 17, -1000, 8,
	-20, -1000, 13, -1000, -1000, 6, 35, 19, 2, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 29, -1000, -1000, -1000, 29, -1, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -6, -1000, 29,
	-1000, -1000,
}

var rulePgo = [...]int8{
	0, 41, 54, 53, 52, 51, 44, 10, 0, 32,
}

var ruleR1 = [...]int8{
	0, 1, 1, 1, 1, 1, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 3, 3, 4,
	4, 4, 4, 5, 5, 5, 6, 6, 7, 7,
	8, 9, 9, 9, 9, 9, 9, 9,
}

var ruleR2 = [...]int8{
	0, 1, 3, 3, 2, 3, 4, 4, 4, 4,
	4, 4, 4, 4, 1, 6, 6, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 0, 1, 1, 3,
	1, 1, 1, 1, 1, 1, 1, 1,
}

var ruleChk = [...]int16{
	-1000, -1, -2, 13, 16, 4, 14, 15, -1, -1,
	-6, 13, -1, -1, 17, -5, -3, 28, 29, 21,
	22, 27, -4, 23, 24, 25, 26, 5, 6, 9,
	11, 10, 18, 7, 8, 12, 18, -7, -8, -9,
	5, 7, 8, 9, 11, 10, 6, -7, 19, 20,
	19, -8,
}

var ruleDef = [...]int8{
	0, -2, 1, 0, 0, -2, 0, 0, 4, 0,
	0, 27, 2, 3, 5, 18, 0, 0, 0, 23,
	24, 25, 17, 19, 20, 21, 22, 6, 7, 10,
	11, 12, 0, 8, 9, 13, 0, 0, 28, 30,
	31, 32, 33, 34, 35, 36, 37, 0, 15, 0,
	16, 29,
}

var ruleTok1 = [...]int8{
	1,
}

var ruleTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30,
}

var ruleTok3 = [...]int8{
	0,
}

var ruleErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	ruleDebug        = 0
	ruleErrorVerbose = false
)

type ruleLexer interface {
	Result(n Rule)
	Lex(lval *ruleSymType) int
	Error(s string)
}

type ruleParser interface {
	Parse(ruleLexer) int
	Lookahead() int
}

type ruleParserImpl struct {
	lval  ruleSymType
	stack [ruleInitialStackSize]ruleSymType
	char  int
}

func (p *ruleParserImpl) Lookahead() int {
	return p.char
}

func ruleNewParser() ruleParser {
	return &ruleParserImpl{}
}

const ruleFlag = -1000

func ruleTokname(c int) string {
	if c >= 1 && c-1 < len(ruleToknames) {
		if ruleToknames[c-1] != "" {
			return ruleToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func ruleStatname(s int) string {
	if s >= 0 && s < len(ruleStatenames) {
		if ruleStatenames[s] != "" {
			return ruleStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func ruleErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !ruleErrorVerbose {
		return "syntax error"
	}

	for _, e := range ruleErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + ruleTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(rulePact[state])
	for tok := TOKSTART; tok-1 < len(ruleToknames); tok++ {
		if n := base + tok; n >= 0 && n < ruleLast && int(ruleChk[int(ruleAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if ruleDef[state] == -2 {
		i := 0
		for ruleExca[i] != -1 || int(ruleExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; ruleExca[i] >= 0; i += 2 {
			tok := int(ruleExca[i])
			if tok < TOKSTART || ruleExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if ruleExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += ruleTokname(tok)
	}
	return res
}

func rulelex1(lex ruleLexer, lval *ruleSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(ruleTok1[0])
		goto out
	}
	if char < len(ruleTok1) {
		token = int(ruleTok1[char])
		goto out
	}
	if char >= rulePrivate {
		if char < rulePrivate+len(ruleTok2) {
			token = int(ruleTok2[char-rulePrivate])
			goto out
		}
	}
	for i := 0; i < len(ruleTok3); i += 2 {
		token = int(ruleTok3[i+0])
		if token == char {
			token = int(ruleTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(ruleTok2[1]) /* unknown char */
	}
	if ruleDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", ruleTokname(token), uint(char))
	}
	return char, token
}

func ruleParse(rulelex ruleLexer) int {
	return ruleNewParser().Parse(rulelex)
}

func (rulercvr *ruleParserImpl) Parse(rulelex ruleLexer) int {
	var rulen int
	var ruleVAL ruleSymType
	var ruleDollar []ruleSymType
	_ = ruleDollar // silence set and not used
	ruleS := rulercvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	rulestate := 0
	rulercvr.char = -1
	ruletoken := -1 // rulercvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		rulestate = -1
		rulercvr.char = -1
		ruletoken = -1
	}()
	rulep := -1
	goto rulestack

ret0:
	return 0

ret1:
	return 1

rulestack:
	/* put a state and value onto the stack */
	if ruleDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", ruleTokname(ruletoken), ruleStatname(rulestate))
	}

	rulep++
	if rulep >= len(ruleS) {
		nyys := make([]ruleSymType, len(ruleS)*2)
		copy(nyys, ruleS)
		ruleS = nyys
	}
	ruleS[rulep] = ruleVAL
	ruleS[rulep].yys = rulestate

rulenewstate:
	rulen = int(rulePact[rulestate])
	if rulen <= ruleFlag {
		goto ruledefault /* simple state */
	}
	if rulercvr.char < 0 {
		rulercvr.char, ruletoken = rulelex1(rulelex, &rulercvr.lval)
	}
	rulen += ruletoken
	if rulen < 0 || rulen >= ruleLast {
		goto ruledefault
	}
	rulen = int(ruleAct[rulen])
	if int(ruleChk[rulen]) == ruletoken { /* valid shift */
		rulercvr.char = -1
		ruletoken = -1
		ruleVAL = rulercvr.lval
		rulestate = rulen
		if Errflag > 0 {
			Errflag--
		}
		goto rulestack
	}

ruledefault:
	/* default state action */
	rulen = int(ruleDef[rulestate])
	if rulen == -2 {
		if rulercvr.char < 0 {
			rulercvr.char, ruletoken = rulelex1(rulelex, &rulercvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if ruleExca[xi+0] == -1 && int(ruleExca[xi+1]) == rulestate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			rulen = int(ruleExca[xi+0])
			if rulen < 0 || rulen == ruletoken {
				break
			}
		}
		rulen = int(ruleExca[xi+1])
		if rulen < 0 {
			goto ret0
		}
	}
	if rulen == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			rulelex.Error(ruleErrorMessage(rulestate, ruletoken))
			Nerrs++
			if ruleDebug >= 1 {
				__yyfmt__.Printf("%s", ruleStatname(rulestate))
				__yyfmt__.Printf(" saw %s\n", ruleTokname(ruletoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for rulep >= 0 {
				rulen = int(rulePact[ruleS[rulep].yys]) + ruleErrCode
				if rulen >= 0 && rulen < ruleLast {
					rulestate = int(ruleAct[rulen]) /* simulate a shift of "error" */
					if int(ruleChk[rulestate]) == ruleErrCode {
						goto rulestack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if ruleDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", ruleS[rulep].yys)
				}
				rulep--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if ruleDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", ruleTokname(ruletoken))
			}
			if ruletoken == ruleEofCode {
				goto ret1
			}
			rulercvr.char = -1
			ruletoken = -1
			goto rulenewstate /* try again in the same state */
		}
	}

	/* reduction by production rulen */
	if ruleDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", rulen, ruleStatname(rulestate))
	}

	rulent := rulen
	rulept := rulep
	_ = rulept // guard against "declared and not used"

	rulep -= int(ruleR2[rulen])
	// rulep is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if rulep+1 >= len(ruleS) {
		nyys := make([]ruleSymType, len(ruleS)*2)
		copy(nyys, ruleS)
		ruleS = nyys
	}
	ruleVAL = ruleS[rulep+1]

	/* consult goto table to find next state */
	rulen = int(ruleR1[rulen])
	ruleg := int(rulePgo[rulen])
	rulej := ruleg + ruleS[rulep].yys + 1

	if rulej >= ruleLast {
		rulestate = int(ruleAct[ruleg])
	} else {
		rulestate = int(ruleAct[rulej])
		if int(ruleChk[rulestate]) != -rulen {
			rulestate = int(ruleAct[ruleg])
		}
	}
	// dummy call; replaced with literal code
	switch rulent {

	case 1:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:240
		{
			ruleVAL.rule = ruleDollar[1].rule
			rulelex.Result(ruleVAL.rule)
		}
	case 2:
		ruleDollar = ruleS[rulept-3 : rulept+1]
//line parser.y:245
		{
			ruleVAL.rule = &nodeAnd{left: ruleDollar[1].rule, right: ruleDollar[3].rule}
			rulelex.Result(ruleVAL.rule)
		}
	case 3:
		ruleDollar = ruleS[rulept-3 : rulept+1]
//line parser.y:250
		{
			ruleVAL.rule = &nodeOr{left: ruleDollar[1].rule, right: ruleDollar[3].rule}
			rulelex.Result(ruleVAL.rule)
		}
	case 4:
		ruleDollar = ruleS[rulept-2 : rulept+1]
//line parser.y:255
		{
			ruleVAL.rule = &nodeNot{right: ruleDollar[2].rule}
			rulelex.Result(ruleVAL.rule)
		}
	case 5:
		ruleDollar = ruleS[rulept-3 : rulept+1]
//line parser.y:260
		{
			ruleVAL.rule = ruleDollar[2].rule
			rulelex.Result(ruleVAL.rule)
		}
	case 6:
		ruleDollar = ruleS[rulept-4 : rulept+1]
//line parser.y:268
		{
			field := string(ruleDollar[1].data)
			negate := ruleDollar[2].negate
			op := ruleDollar[3].operator

			elem, err := parseToken(token_STRING, ruleDollar[4].data)
			if err != nil {
				rulelex.Error(err.Error())
				return 1
			}

			ruleVAL.rule = withNegate(negate, &nodeCompare{
				predicate: predicate{field: field, raw_value: elem.raw_value},
				op:        op,
				value:     elem.value,
			})
		}
	case 7:
		ruleDollar = ruleS[rulept-4 : rulept+1]
//line parser.y:286
		{
			field := string(ruleDollar[1].data)
			negate := ruleDollar[2].negate
			op := ruleDollar[3].operator

			elem, err := parseToken(token_HEX_STRING, ruleDollar[4].data)
			if err != nil {
				rulelex.Error(err.Error())
				return 1
			}
			ruleVAL.rule = withNegate(negate, &nodeCompare{
				predicate: predicate{field: field, raw_value: elem.raw_value},
				op:        op,
				value:     elem.value,
			})
		}
	case 8:
		ruleDollar = ruleS[rulept-4 : rulept+1]
//line parser.y:303
		{
			field := string(ruleDollar[1].data)
			negate := ruleDollar[2].negate
			op := ruleDollar[3].operator

			elem, err := parseToken(token_INT, ruleDollar[4].data)
			if err != nil {
				rulelex.Error(err.Error())
				return 1
			}

			ruleVAL.rule = withNegate(negate, &nodeCompare{
				predicate: predicate{field: field, raw_value: elem.raw_value},
				op:        op,
				value:     elem.value,
			})
		}
	case 9:
		ruleDollar = ruleS[rulept-4 : rulept+1]
//line parser.y:321
		{
			field := string(ruleDollar[1].data)
			negate := ruleDollar[2].negate
			op := ruleDollar[3].operator

			elem, err := parseToken(token_FLOAT, ruleDollar[4].data)
			if err != nil {
				rulelex.Error(err.Error())
				return 1
			}

			ruleVAL.rule = withNegate(negate, &nodeCompare{
				predicate: predicate{field: field, raw_value: elem.raw_value},
				op:        op,
				value:     elem.value,
			})
		}
	case 10:
		ruleDollar = ruleS[rulept-4 : rulept+1]
//line parser.y:339
		{
			field := string(ruleDollar[1].data)
			negate := ruleDollar[2].negate
			op := ruleDollar[3].operator

			elem, err := parseToken(token_BOOL, ruleDollar[4].data)
			if err != nil {
				rulelex.Error(err.Error())
				return 1
			}

			ruleVAL.rule = withNegate(negate, &nodeCompare{
				predicate: predicate{field: field, raw_value: elem.raw_value},
				op:        op,
				value:     elem.value,
			})
		}
	case 11:
		ruleDollar = ruleS[rulept-4 : rulept+1]
//line parser.y:357
		{
			field := string(ruleDollar[1].data)
			negate := ruleDollar[2].negate
			op := ruleDollar[3].operator

			elem, err := parseToken(token_IP, ruleDollar[4].data)
			if err != nil {
				rulelex.Error(err.Error())
				return 1
			}

			ruleVAL.rule = withNegate(negate, &nodeCompare{
				predicate: predicate{field: field, raw_value: elem.raw_value},
				op:        op,
				value:     elem.value,
			})
		}
	case 12:
		ruleDollar = ruleS[rulept-4 : rulept+1]
//line parser.y:375
		{
			field := string(ruleDollar[1].data)
			negate := ruleDollar[2].negate
			op := ruleDollar[3].operator

			elem, err := parseToken(token_IP_CIDR, ruleDollar[4].data)
			if err != nil {
				rulelex.Error(err.Error())
				return 1
			}

			ruleVAL.rule = withNegate(negate, &nodeCompare{
				predicate: predicate{field: field, raw_value: elem.raw_value},
				op:        op,
				value:     elem.value,
			})
		}
	case 13:
		ruleDollar = ruleS[rulept-4 : rulept+1]
//line parser.y:393
		{
			field := string(ruleDollar[1].data)
			negate := ruleDollar[2].negate

			elem, err := parseToken(token_REGEX, ruleDollar[4].data)
			if err != nil {
				rulelex.Error(err.Error())
				return 1
			}

			ruleVAL.rule = withNegate(negate, &nodeMatch{
				predicate: predicate{field: field, raw_value: elem.raw_value},
				reg_expr:  elem.value.(*regexp.Regexp),
			})
		}
	case 14:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:410
		{
			ruleVAL.rule = &nodeNotZero{string(ruleDollar[1].data)}
		}
	case 15:
		ruleDollar = ruleS[rulept-6 : rulept+1]
//line parser.y:414
		{
			field := string(ruleDollar[1].data)
			negate := ruleDollar[2].negate
			op := ruleDollar[3].operator
			elements := ruleDollar[5].arrayElems

			ruleVAL.rule = withNegate(negate, &nodeCompare{
				predicate: predicate{
					field:     field,
					raw_value: formatArrayRawValue(elements),
				},
				op:    op,
				value: extractValues(elements),
			})
		}
	case 16:
		ruleDollar = ruleS[rulept-6 : rulept+1]
//line parser.y:430
		{
			field := string(ruleDollar[1].data)
			negate := ruleDollar[2].negate
			elements := ruleDollar[5].arrayElems

			ruleVAL.rule = withNegate(negate, &nodeIn{
				predicate: predicate{
					field:     field,
					raw_value: formatArrayRawValue(elements),
				},
				values: extractValues(elements),
			})
		}
	case 19:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:448
		{
			ruleVAL.operator = op_GT
		}
	case 20:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:449
		{
			ruleVAL.operator = op_GE
		}
	case 21:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:450
		{
			ruleVAL.operator = op_LT
		}
	case 22:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:451
		{
			ruleVAL.operator = op_LE
		}
	case 23:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:455
		{
			ruleVAL.operator = op_EQ
		}
	case 24:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:456
		{
			ruleVAL.operator = op_NE
		}
	case 25:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:457
		{
			ruleVAL.operator = op_CONTAINS
		}
	case 26:
		ruleDollar = ruleS[rulept-0 : rulept+1]
//line parser.y:461
		{
			ruleVAL.negate = false
		}
	case 27:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:462
		{
			ruleVAL.negate = true
		}
	case 28:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:467
		{
			ruleVAL.arrayElems = ruleDollar[1].arrayElems
		}
	case 29:
		ruleDollar = ruleS[rulept-3 : rulept+1]
//line parser.y:471
		{
			ruleVAL.arrayElems = append(ruleDollar[1].arrayElems, ruleDollar[3].arrayElems...)
		}
	case 30:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:478
		{
			elem, err := parseToken(ruleDollar[1].tokType.typ, ruleDollar[1].tokType.data)
			if err != nil {
				rulelex.Error(err.Error())
				return 1
			}
			ruleVAL.arrayElems = []parsedValue{elem}
		}
	case 31:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:490
		{
			ruleVAL.tokType = tokenType{typ: token_STRING, data: ruleDollar[1].data}
		}
	case 32:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:494
		{
			ruleVAL.tokType = tokenType{typ: token_INT, data: ruleDollar[1].data}
		}
	case 33:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:498
		{
			ruleVAL.tokType = tokenType{typ: token_FLOAT, data: ruleDollar[1].data}
		}
	case 34:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:502
		{
			ruleVAL.tokType = tokenType{typ: token_BOOL, data: ruleDollar[1].data}
		}
	case 35:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:506
		{
			ruleVAL.tokType = tokenType{typ: token_IP, data: ruleDollar[1].data}
		}
	case 36:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:510
		{
			ruleVAL.tokType = tokenType{typ: token_IP_CIDR, data: ruleDollar[1].data}
		}
	case 37:
		ruleDollar = ruleS[rulept-1 : rulept+1]
//line parser.y:514
		{
			ruleVAL.tokType = tokenType{typ: token_HEX_STRING, data: ruleDollar[1].data}
		}
	}
	goto rulestack /* stack new state and value */
}
