// Parser for rulekit — generated by bison + rust-bison-skeleton.
// Mirrors the Go parser.y grammar, producing Rust AST types.

%expect 0

%define api.parser.struct {Parser}
%define api.value.type {Value}
%define api.parser.check_debug { self.debug }

%define parse.error custom
%define parse.trace

%code use {
    use crate::ast::{Expr, Operator, LiteralValue};
    use crate::types::{Token, Loc, Value, Node, Op, NodeList};
    use crate::lexer::Lexer;
}

%code parser_fields {
    pub result: Option<Expr>,
    pub debug: bool,
}

// Value-carrying tokens
%token
    TOKEN_FIELD       "FIELD"
    TOKEN_FUNCTION    "FUNCTION"
    TOKEN_STRING      "STRING"
    TOKEN_HEX_STRING  "HEX_STRING"
    TOKEN_INT         "INT"
    TOKEN_FLOAT       "FLOAT"
    TOKEN_BOOL        "BOOL"
    TOKEN_IP_CIDR     "IP_CIDR"
    TOKEN_IP          "IP"
    TOKEN_REGEX       "REGEX"
    OP_NOT            "NOT"
    OP_AND            "AND"
    OP_OR             "OR"
    TOKEN_LPAREN      "("
    TOKEN_RPAREN      ")"
    TOKEN_LBRACKET    "["
    TOKEN_RBRACKET    "]"
    TOKEN_COMMA       ","
    OP_EQ             "=="
    OP_NE             "!="
    OP_GT             ">"
    OP_GE             ">="
    OP_LT             "<"
    OP_LE             "<="
    OP_CONTAINS       "CONTAINS"
    OP_MATCHES        "MATCHES"
    OP_IN             "IN"
    TOKEN_ERROR       "ERROR"

%type <Node> search_condition predicate
%type <Node> function_call
%type <Op> ineq_operator eq_operator
%type <NodeList> array_values
%type <Node> value_token
%type <Node> numeric_value_token
%type <Node> array_value_token
%type <Node> array_or_single_value_token
%type <NodeList> function_arguments

// Operator precedence
%left "AND"
%left "OR"
%right "NOT"

%%

search_condition:
    predicate
    {
        let e = Node::from($1);
        self.result = Some(e.clone());
        $$ = Value::Node(e);
    }
    | search_condition "AND" search_condition
    {
        let e = Expr::And {
            left:  Box::new(Node::from($1)),
            right: Box::new(Node::from($3)),
        };
        self.result = Some(e.clone());
        $$ = Value::Node(e);
    }
    | search_condition "OR" search_condition
    {
        let e = Expr::Or {
            left:  Box::new(Node::from($1)),
            right: Box::new(Node::from($3)),
        };
        self.result = Some(e.clone());
        $$ = Value::Node(e);
    }
    | "NOT" search_condition
    {
        let e = Expr::Not {
            expr: Box::new(Node::from($2)),
        };
        self.result = Some(e.clone());
        $$ = Value::Node(e);
    }
    | "(" search_condition ")"
    {
        let e = Node::from($2);
        self.result = Some(e.clone());
        $$ = Value::Node(e);
    }
    ;

predicate:
    // numeric values accept additional inequality operators
    numeric_value_token ineq_operator numeric_value_token
    {
        $$ = Value::Node(Expr::Compare {
            left:  Box::new(Node::from($1)),
            op:    Op::from($2),
            right: Box::new(Node::from($3)),
        });
    }
    // all values including numeric accept equality operators
    | array_or_single_value_token eq_operator array_or_single_value_token
    {
        $$ = Value::Node(Expr::Compare {
            left:  Box::new(Node::from($1)),
            op:    Op::from($2),
            right: Box::new(Node::from($3)),
        });
    }
    // matches supports regex values
    | array_or_single_value_token "MATCHES" "REGEX"
    {
        let rv = parse_value_token(Lexer::TOKEN_REGEX, &$<Token>3.token_value);
        $$ = Value::Node(Expr::Match {
            left:  Box::new(Node::from($1)),
            right: Box::new(rv),
        });
    }
    | array_or_single_value_token
    {
        $$ = $1;
    }
    // in supports array values
    | array_or_single_value_token "IN" array_value_token
    {
        $$ = Value::Node(Expr::In {
            left:  Box::new(Node::from($1)),
            right: Box::new(Node::from($3)),
        });
    }
    // in supports IP CIDR values
    | array_or_single_value_token "IN" "IP_CIDR"
    {
        let rv = parse_value_token(Lexer::TOKEN_IP_CIDR, &$<Token>3.token_value);
        $$ = Value::Node(Expr::Compare {
            left:  Box::new(Node::from($1)),
            op:    Operator::Eq,
            right: Box::new(rv),
        });
    }
    ;

ineq_operator:
    ">"       { $$ = Value::Op(Operator::Gt); }
    | ">="    { $$ = Value::Op(Operator::Ge); }
    | "<"     { $$ = Value::Op(Operator::Lt); }
    | "<="    { $$ = Value::Op(Operator::Le); }
    ;

eq_operator:
    "=="          { $$ = Value::Op(Operator::Eq);       }
    | "!="        { $$ = Value::Op(Operator::Ne);       }
    | "CONTAINS"  { $$ = Value::Op(Operator::Contains); }
    ;

// Array handling rules
array_values:
    value_token
    {
        $$ = Value::NodeList(vec![Node::from($1)]);
    }
    | array_values "," value_token
    {
        let mut v = NodeList::from($1);
        v.push(Node::from($3));
        $$ = Value::NodeList(v);
    }
    ;

array_value_token:
    "[" array_values "]"
    {
        $$ = Value::Node(Expr::Array(NodeList::from($2)));
    }
    ;

array_or_single_value_token:
    function_call       { $$ = $1; }
    | value_token       { $$ = $1; }
    | array_value_token { $$ = $1; }
    ;

// value tokens
value_token:
    numeric_value_token { $$ = $1; }
    | "STRING"
    {
        $$ = Value::Node(parse_value_token(Lexer::TOKEN_STRING, &$<Token>1.token_value));
    }
    | "BOOL"
    {
        $$ = Value::Node(parse_value_token(Lexer::TOKEN_BOOL, &$<Token>1.token_value));
    }
    | "IP"
    {
        $$ = Value::Node(parse_value_token(Lexer::TOKEN_IP, &$<Token>1.token_value));
    }
    | "IP_CIDR"
    {
        $$ = Value::Node(parse_value_token(Lexer::TOKEN_IP_CIDR, &$<Token>1.token_value));
    }
    | "HEX_STRING"
    {
        $$ = Value::Node(parse_value_token(Lexer::TOKEN_HEX_STRING, &$<Token>1.token_value));
    }
    | "REGEX"
    {
        $$ = Value::Node(parse_value_token(Lexer::TOKEN_REGEX, &$<Token>1.token_value));
    }
    ;

numeric_value_token:
    "INT"
    {
        $$ = Value::Node(parse_value_token(Lexer::TOKEN_INT, &$<Token>1.token_value));
    }
    | "FLOAT"
    {
        $$ = Value::Node(parse_value_token(Lexer::TOKEN_FLOAT, &$<Token>1.token_value));
    }
    | "FIELD"
    {
        let name = String::from_utf8_lossy(&$<Token>1.token_value).to_string();
        $$ = Value::Node(Expr::Field(name));
    }
    | "FUNCTION"
    {
        // An isolated function name (no parens) is treated as a field reference,
        // just like the Go version.
        let name = String::from_utf8_lossy(&$<Token>1.token_value).to_string();
        $$ = Value::Node(Expr::Field(name));
    }
    ;

function_call:
    "FUNCTION" "(" function_arguments ")"
    {
        let name = String::from_utf8_lossy(&$<Token>1.token_value).to_string();
        $$ = Value::Node(Expr::FunctionCall {
            name,
            args: NodeList::from($3),
        });
    }
    ;

function_arguments:
    array_or_single_value_token
    {
        $$ = Value::NodeList(vec![Node::from($1)]);
    }
    | function_arguments "," array_or_single_value_token
    {
        let mut v = NodeList::from($1);
        v.push(Node::from($3));
        $$ = Value::NodeList(v);
    }
    | /* nothing */
    {
        $$ = Value::NodeList(Vec::new());
    }
    ;

%%

impl Parser {
    pub fn new(lexer: Lexer) -> Self {
        Self {
            yy_error_verbose: true,
            yynerrs: 0,
            debug: false,
            yyerrstatus_: 0,
            yylexer: lexer,
            result: None,
        }
    }

    pub fn do_parse(mut self) -> Option<Expr> {
        self.parse();
        self.result
    }

    fn next_token(&mut self) -> Token {
        self.yylexer.yylex()
    }

    fn report_syntax_error(&self, _stack: &YYStack, _yytoken: &SymbolKind, _loc: YYLoc) {
        eprintln!("syntax error");
    }
}

/// Convert raw token bytes into an `Expr::Literal`.
fn parse_value_token(token_type: i32, raw: &[u8]) -> Expr {
    let s = String::from_utf8_lossy(raw).to_string();
    let lit = match token_type {
        Lexer::TOKEN_STRING     => LiteralValue::String(parse_string(&s)),
        Lexer::TOKEN_INT        => LiteralValue::Int(s.parse::<i64>().unwrap_or(0)),
        Lexer::TOKEN_FLOAT      => LiteralValue::Float(s.parse::<f64>().unwrap_or(0.0)),
        Lexer::TOKEN_BOOL       => LiteralValue::Bool(s.eq_ignore_ascii_case("true")),
        Lexer::TOKEN_IP         => {
            let ip: std::net::IpAddr = s.parse().unwrap();
            LiteralValue::Ip(ip)
        }
        Lexer::TOKEN_IP_CIDR    => LiteralValue::IpCidr(s),
        Lexer::TOKEN_HEX_STRING => LiteralValue::HexString(parse_hex_string(&s)),
        Lexer::TOKEN_REGEX      => LiteralValue::Regex(parse_regex(&s)),
        _ => panic!("unknown token type: {}", token_type),
    };
    Expr::Literal(lit)
}

fn parse_string(s: &str) -> String {
    if s.len() < 2 { return s.to_string(); }
    let inner = &s[1..s.len() - 1];
    let mut out = String::with_capacity(inner.len());
    let mut chars = inner.chars();
    while let Some(c) = chars.next() {
        if c == '\\' {
            match chars.next() {
                Some('n')  => out.push('\n'),
                Some('t')  => out.push('\t'),
                Some('r')  => out.push('\r'),
                Some('"')  => out.push('"'),
                Some('\'') => out.push('\''),
                Some('\\') => out.push('\\'),
                Some(other) => { out.push('\\'); out.push(other); }
                None => out.push('\\'),
            }
        } else {
            out.push(c);
        }
    }
    out
}

fn parse_hex_string(s: &str) -> Vec<u8> {
    s.split(':')
        .filter_map(|part| u8::from_str_radix(part, 16).ok())
        .collect()
}

fn parse_regex(s: &str) -> String {
    if s.len() < 2 { return s.to_string(); }
    s[1..s.len() - 1].to_string()
}
